### ISSUE TITLE
Alerte jaune et orange

### ISSUE THREAD

**Issue by tikismoke** [Imbuzi/meteo-france-weather-card#1]
Nous avons une alerte jaune et orange en même temps, mais pas d'icones pour la orage:

![Screenshot_20200510_230450](https://user-images.githubusercontent.com/2229691/81510541-b2ff6d80-9312-11ea-842d-198c0a79c56c.png)
![Screenshot_20200510_230427](https://user-images.githubusercontent.com/2229691/81510543-b4309a80-9312-11ea-8299-2bd584b4a59a.png)

cas surement rare mais pas WAF :(

**Comment by Imbuzi** [comment]
J'ai effectivement constaté le même bug hier, et j'ai trouvé d'ou vient le problème.

En effet, il est possible d'avoir des alertes de plusieurs couleurs en même temps. Par contre, l'icône pour l'alerte "Pluie-inondation" n'est jamais affichée.

C'est lié à l'intégration de Météo France dans HA, qui ne remonte pas une alerte "Pluie-inondation", mais "Pluie-innodation". Ca vient même de l'utilisation d'une ressource externe, sur laquelle j'ai ouvert une [PR](https://github.com/oncleben31/vigilancemeteo/pull/10) qui a été mergée hier.

Reste à voir pour faire remonter ce correctif jusque dans HA (je suis en train d'investiguer).

Je laisse cette issue ouverte tant que ce n'est pas résolu.

**Comment by tikismoke** [comment]
Ha oui j'avais pas poussé mes recherches jusque là désolé... D'habitude je le fais, j'avoue m'être arrêté a la visualisation pas l'origine du problème.

Effectivement si y a une erreur dans la lib de départ ça va pas aider.

Wait&see :)

En tout cas merci pour ce 'widget' il marque des points dans ma migration vers hassio auprès de tout le monde Mme des enfants (en bas âge).

J'adorerais avoir la même chose pour ma gestion du pollens (faite maison a base nodered et l'addons homeassistant en récupérant les infos sur le site pollens.fr)

Le 11 mai 2020 09:37:51 GMT+02:00, Nicolas Bourasseau <notifications@github.com> a écrit :
>J'ai effectivement constaté le même bug hier, et j'ai trouvé d'ou vient
>le problème.>
>>
>En effet, il est possible d'avoir des alertes de plusieurs couleurs en
>même temps. Par contre, l'icône pour l'alerte "Pluie-inondation" n'est
>jamais affichée.>
>>
>C'est lié à l'intégration de Météo France dans HA, qui ne remonte pas
>une alerte "Pluie-inondation", mais "Pluie-innodation". Ca vient même
>de l'utilisation d'une ressource externe, sur laquelle j'ai ouvert une
>[PR](https://github.com/oncleben31/vigilancemeteo/pull/10) qui a été
>mergée hier.>
>>
>Reste à voir pour faire remonter ce correctif jusque dans HA (je suis
>en train d'investiguer).>
>>
>Je laisse cette issue ouverte tant que ce n'est pas résolu.>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/Imbuzi/meteo-france-weather-card/issues/1#issuecomment-626527492

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

Attention nous avons changer de domaine, utilisez poudot.fr à la place de tikijs.dyndns.org

**Comment by Imbuzi** [comment]
Petite update :

Ma PR sur la lib a été acceptée et mergée (intégré dans la [v3.0.1](https://github.com/oncleben31/vigilancemeteo/tree/v3.0.1).

Reste à updater les versions des dépendances côté HA pour que ce soit déployé. Je continue pour essayer d'avoir ça dans une release rapidement.

Au sujet de ton intégration de pollens.fr, ça m'intéresse pas mal aussi !
Si tu as les compétences, ça serait cool d'intégrer ça dans une intégration sur HA (ou sur HACS), et je pourrais en effet faire une carte Lovelace pour afficher tout ça proprement.

**Comment by tikismoke** [comment]
Pour le moment j'ai un components sur le plcbus a faire fonctionner en premier. Le pollens sera peut être dans une fil d'attente encore un petit temps.

Mais je note ne pas être le seul intéressé et que tu pourrais faire une jolie card :(

**Comment by Imbuzi** [comment]
Ok ça marche, n'hésite pas à me tenir au jus :)

Encore une petite update sur la correction du bug Météo France : la [PR](https://github.com/home-assistant/core/pull/35537) côté HA a été acceptée et mergée sur la branche dev pour intégrer le correctif.

Maintenant, plus qu'a attendre la mise en prod. 

Wait & see ...

**Comment by rParslow** [comment]
> Au sujet de ton intégration de pollens.fr, ça m'intéresse pas mal aussi !

Haaaa
Je peux essayer de regarder cela de mon coté

**Comment by tikismoke** [comment]
> > Au sujet de ton intégration de pollens.fr, ça m'intéresse pas mal aussi !
> 
> Haaaa
> Je peux essayer de regarder cela de mon coté

Je te file les infos dans la soirée.
J'avoue que si quelqu'un peut si coller ça m'arrangerai...

**Comment by rParslow** [comment]
> Je te file les infos dans la soirée.

Je pensais aller regarder comment c'était fait dans Jee Dom :)

**Comment by tikismoke** [comment]
Suffit de parser la réponses a ça en gros:

https://www.pollens.fr/risks/thea/counties/39

**Comment by Imbuzi** [comment]
Dernières news au sujet de la card Lovelace pour l'alerte "Pluie-inondation" :

C'est corrigé et déployé sur la version beta de HA ! Et comme il fait un temps de merde aujourd'hui, j'ai même pu tester la belle icône et ça marche.

![image](https://user-images.githubusercontent.com/20660653/81909356-c50b3580-95ca-11ea-9fae-78c5016705df.png)

Je clos donc cette issue. Pour la corriger de votre côté, deux solutions : 
- Soit switcher sur la dernière version beta (honnêtement, c'est risque de passer sur une version pas stable pour juste une icône)
- Soit attendre la prochaine release (qui ne devrait pas trop tarder)

N'hésitez pas à monter une discussion pour le point sur pollens.fr, ça m'intéresse vraiment, et je pourrais éventuellement bosser sur une card pour afficher tout ça !

**Comment by rParslow** [comment]
> Suffit de parser la réponses a ça en gros:
> https://www.pollens.fr/risks/thea/counties/39

Bon comme je débute aussi c'est pas encore tout à fait çà 

![image](https://user-images.githubusercontent.com/1121777/81990589-bb6fe500-963f-11ea-9654-ff21bbb8b03a.png)


`  - platform: rest
    name: Pollens
    json_attributes_path: "$.risks[0]"
    json_attributes:
      - pollenName
      - level
    resource: https://www.pollens.fr/risks/thea/counties/39
#    value_template: '{{ value_json.countyName }}'
    value_template: >
      {% for x in value_json %}
        '{{ loop.index }}. {{ x.pollenName }}'
      {% endfor %}`

**Comment by tikismoke** [comment]
> @tikismoke @Imbuzi
> c'est suffisant d'avoir les pollens en attribut comme ceci où il faut un sensor par allergène ?
> 
> j'ai utilisé un sensor / rest
> par contre je ne sais pas comment forcer icon: mdi:allergy autrement que par une surcharge UI :(
> 
> ```
> risks:
>   - pollenName: Tilleul
>     level: 0
>   - pollenName: Ambroisies
>     level: 0
>   - pollenName: Olivier
>     level: 0
>   - pollenName: Plantain
>     level: 2
>   - pollenName: Noisetier
>     level: 0
>   - pollenName: Aulne
>     level: 0
> ```
> 
> ![image](https://user-images.githubusercontent.com/1121777/82081319-5f13d080-96e6-11ea-8532-ff215f497f98.png)
> 
> ```
> sensor:
>   - platform: rest
>     name: Pollens
>     resource: https://www.pollens.fr/risks/thea/counties/39    
>     json_attributes:
>       - risks
>     value_template: '{{ value_json.riskLevel }}'
>     # Request every 12 hours
>     scan_interval: 43200
> ```

Sorry i miss the notification.
I created a thread in community.
So we could share easily.

https://community.home-assistant.io/t/get-allergy-for-french/197559
