### ISSUE TITLE
CPU Issue with animated Icons

### ISSUE THREAD

**Issue by olivier6931** [Imbuzi/meteo-france-weather-card#11]
Hi,

It's a very nice card you developped! Thanks for it :)

By the way, I noticed my CPU exploded on the raspberry I used to display my home assistant dashboard, when using this card. 
Leading it to heat to 80° and throttle...
This is due to animated Icons on amCharts.

Their aspect are very nice, and I noticed also that amCharts provide static Icons (which doesn't charge CPU) : https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/icons/static/

Is it possible to add an element of configuration to have the choice between animated and static icon, please ?

Thank you for your work again!

**Comment by TheDeathSpirit** [comment]
Agreed : great card! I hope it will support the next breaking changes in meteofrance HA integration.

I have the same issue with animated svg, it makes it veeeeeeeeery slow on HAcompanion on android (no issue in the web browser). I see that there is an option to change icon packs, but I don't really know how to use it... I've tried to add [icon: "https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/icons/static/"] to the card conf, but no changes...

Thank you for this beautiful card ! ;)

**Comment by sr-as2** [comment]
Same issue, if we can have a static icon version, that's great!

**Comment by mycanaletto** [comment]
+1

**Comment by olivier6931** [comment]
> 
> 
> Agreed : great card! I hope it will support the next breaking changes in meteofrance HA integration.
> 
> I have the same issue with animated svg, it makes it veeeeeeeeery slow on HAcompanion on android (no issue in the web browser). I see that there is an option to change icon packs, but I don't really know how to use it... I've tried to add [icon: "https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/icons/static/"] to the card conf, but no changes...
> 
> Thank you for this beautiful card ! ;)

Hello,

I found this solution too, and the exact syntaxe is : 
 icons: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/icons/static/
(with an S), or directly in the field under your location.

I close this issue, as it's solved for me.

Have a nice day!
