### ISSUE TITLE
Prepare for next meteo_france version

### ISSUE THREAD

**Issue by oncleben31** [Imbuzi/meteo-france-weather-card#12]
We have worked hard on the future version of `meteo_france`. [The PR](https://github.com/home-assistant/core/pull/37737) will be reviewed soon and probably merged.
There are some breaking changes who could have an impact on your card.

**Comment by tikismoke** [comment]
Next rain is no more working as it's timestamp based now.

**Comment by oncleben31** [comment]
We received some feedback from the first users. We will change the attributes of this sensor to avoid having changing keys.

**Comment by tikismoke** [comment]
> We received some feedback from the first users. We will change the attributes of this sensor to avoid having changing keys.

You mean it will be back like before?

**Comment by oncleben31** [comment]
Not sure. Because in the previous version this attribute was not easy to understand.

**Comment by oncleben31** [comment]
As soon as [this PR](https://github.com/home-assistant/core/pull/39092) will be merged it will be feasible to update this card to make it work again

**Comment by oncleben31** [comment]
The PR is merged and the new attributes will be available in next version.
@Imbuzi you can update the rain forecast part.
