### ISSUE TITLE
Weather condition not translated

### ISSUE THREAD

**Issue by juanpa669** [Imbuzi/meteo-france-weather-card#14]
Hi, 

First, thanks for this beautiful card

I got no translation on weather condition and the alert display is collide UV

![image](https://user-images.githubusercontent.com/30127385/89739023-80821f80-da7d-11ea-8329-781adccf905b.png)

**Comment by tibortiz** [comment]
@juanpa669 Weird, the icon on the left should dislplay the pourcentage of the risk of rain and not the weather condition. Maybe you defined the wrong entity for `rainChanceEntity`. Could you post your card configuration ?

**Comment by juanpa669** [comment]
Ok I see. The labels of the input fields were not present when the map was created. It was only when I wanted to modify that the labels appeared and there I realized that they were not in their respective places. On the other hand, I do not have a thunderstorm risk entity

![image](https://user-images.githubusercontent.com/30127385/89769477-799af180-dafd-11ea-87a0-a64617f5edc7.png)
