### ISSUE TITLE
URL changed between versions

### ISSUE THREAD

**Issue by ThibaultPelloquin** [Imbuzi/meteo-france-weather-card#2]
For v. 1.1, URL is :
https://cdn.jsdelivr.net/gh/Imbuzi/meteo-france-weather-card@1.1/weather-card.js

But for v. 1.5, "dist/meteo-france-" string has been inserted in the URL:
https://cdn.jsdelivr.net/gh/Imbuzi/meteo-france-weather-card@1.5/dist/meteo-france-weather-card.js

¯\_(ツ)_/¯

**Comment by Imbuzi** [comment]
Since the integration in HACS, "dist/" has been added to the path, and the file was renamed from "weather-card.js" to "meteo-france-weather-card.js".

Didn't realise this was a breakling change.

I'm updating README.md to add "dist/" in path.
