### ISSUE TITLE
problème de configuration carte avec installation HACS

### ISSUE THREAD

**Issue by rParslow** [Imbuzi/meteo-france-weather-card#3]
Bonjour,

J'ai intégré le modèle depuis HACS, J'ajoute donc une custom-card avec   
type: 'custom:meteo-france-weather-card'

Il y a deux jours j'avais bien dans le mode éditeur visuel, Mais il y avait quelques petits problèmes de configuration, ce jour après l'update en supprimant et reconstruisant ma carte, je me suis retrouvé avec des éléments en moins et j'ai constaté toujours qu'il semblait y avoir un mismatch entre l'entité et le descripteur. 
par exemple rain/freeze uv/next_rain, … 

```
type: 'custom:meteo-france-weather-card'
name: Ici
entity: sensor.ville_weather
rainChanceEntity: sensor.ville_freeze_chance
uvEntity: sensor.ville_next_rain
thunderChanceEntity: sensor.ville_uv
freezeChanceEntity: sensor.ville_temperature
snowChanceEntity: sensor.ville_thunder_chance
```

De plus, j'ai perdu l'affichage de l'animation de la température et des projections sur les jours à venir.

Serait-il possible d'avoir un exemple complet de configuration dans le readMe ? 

![image](https://user-images.githubusercontent.com/1121777/81829814-9a25d080-953b-11ea-91b7-f0d8410cef47.png)

**Comment by rParslow** [comment]
J'ai tout supprimé puis réinstallé 
et c'est mieux :) 

Ce serait bien de mettre ceci dans le ReadMe 

```
type: 'custom:meteo-france-weather-card'
name: Ville
entity: weather.ville
rainForecastEntity: sensor.ville_next_rain
freezeChanceEntity: sensor.ville_freeze_chance
rainChanceEntity: sensor.ville_rain_chance
snowChanceEntity: sensor.ville_snow_chance
thunderChanceEntity: sensor.ville_thunder_chance
alertEntity: sensor.ville_weather_alert
uvEntity: sensor.ville_uv
```
Il n'y a pas d'autres paramètres ?

**Comment by Imbuzi** [comment]
Étrange ce bug ...

Pour la config sample, je vais mettre ça dans le README, bonne idée !

Enfin, l'exemple que tu as mis est quasi complet. Il est aussi possible d'initialiser l'attribut "icon" pour utiliser une autre bibliothèque d’icônes que celle fournie de base.

**Comment by magicbret** [comment]
Merci pour ce post car je n'avais aucune idée des paramètres à entrer. C'est pas documenté :( Tu as trouvé çà ou @rParslow les paramètres ?

En tous cas çà marche bien maintenant ;)

**Comment by rParslow** [comment]
> Tu as trouvé çà où?

Pour partie certains sont arrivés en autocompletion en mettant sensor.ville*
Puis après je suis allé regarder dans le code :)
Mais il en manque peut être 

@Imbuzi tu pourras donner un exemple pour une bibli alternative d'icônes ?
Il y a peut être d'autres paramètres qui manquent ?

**Comment by magicbret** [comment]
Pardon je me suis mal exprimé, en fait je parlais des titres rainForecastEntity, freezeChanceEntity etc... a part dans le code effectivement. Mais merci ;)

**Comment by rParslow** [comment]
> je parlais des titres rainForecastEntity, freezeChanceEntity etc...

La première fois je suis tombé sur la carte avec les différents titres ou j'ai remplis :) 
mais ensuite je ne l'ai plus vu 
et j'ai été vir dans le code :) 
![image](https://user-images.githubusercontent.com/1121777/81942559-8c835000-95fa-11ea-8a03-1fb95d029fe8.png)

**Comment by Imbuzi** [comment]
En effet, quand l'éditeur visuel ne fonctionne pas (ça arrive parfois), aucun moyen de savoir comment configurer tout ça. J'ai donc rajouté ça dans le README.

Pour la bibliothèque d'icônes, je t'avoue que je ne m'en sers pas. C'est une fonctionnalité qui vient du [projet que j'ai forké](https://github.com/bramkragten/weather-card), et je l'ai laissée sans grande conviction de son utilité ...

Peut-être que sur le projet originel, il y a des exemples d'icônes customisées.

**Comment by rParslow** [comment]
> C'est une fonctionnalité qui vient du [projet que j'ai forké](https://github.com/bramkragten/weather-card), et je l'ai laissée sans grande conviction de son utilité

Je regarde 

Et pour avoir la liste des entitées il suffit de regarder ici 

![image](https://user-images.githubusercontent.com/1121777/81946191-57c5c780-95ff-11ea-9f4d-3e67efcd40eb.png)

**Comment by magicbret** [comment]
> 
> Je regarde
> 
> Et pour avoir la liste des entitées il suffit de regarder ici
> 
> ![image](https://user-images.githubusercontent.com/1121777/81946191-57c5c780-95ff-11ea-9f4d-3e67efcd40eb.png)

;) oui oui, pour les entités j'ai bien compris qu'on les retrouvais ici (je débute avec HA, je viens de Domoticz), c'est juste que je trouvais pas la conf qu'il fallait pour afficher les icônes en haut de la carte (les lunettes pour l'UV et les autres icônes pour afficher les différentes risque. Ma conf avant c'était çà 

> 

    - type: custom:meteo-france-weather-card
      name: Météo
      entity: weather.ma_ville
    - type: entities
      title: Alerte météo
      icon: mdi:cloud-alert
      show_header_toggle: false
      entities:
        - sensor.ma_ville_weather_alert
        - sensor.ma_ville_weather
        - sensor.ma_ville_rain_chance
        - sensor.ma_ville_thunder_chance

Donc rien à voir et ca expliquait pourquoi la carte était incomplète :)

Et je suis en mode YAML aussi, ce qui ne simplifie pas les choses, mais je viens de repasser en mode UI, plus facile quand même
