### ISSUE TITLE
Partial weather forecast

### ISSUE THREAD

**Issue by Grui** [Imbuzi/meteo-france-weather-card#7]
Hi,

This morning I have a partial weather forecast : only monday and tuesday. monday without any icon. tested on two different devices, same issues.
![4988AF4E-4BDE-4878-96B7-D61C029E62D7](https://user-images.githubusercontent.com/18003726/82139314-24658180-9827-11ea-9c00-f771e9a88111.jpeg)

**Comment by oncleben31** [comment]
This is not due to the card but due to the meteofrance website.
It seems the errors have disapeared.
You can close this issue.
